# Hyperparameters, model selection, paths


project:
  name: "Glaucoma_Detection_Pipeline"
  seed: 42
  output_dir: "outputs"

data:
  file_path: "data/Data on OCT and Fundus Images"
  img_size: 224
  num_classes: 2

training:
  model_name: "ensemble"  # Options: 'resnet', 'densenet', 'ensemble'
  n_folds: 5
  epochs: 25
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.001
  device: "cuda"          # 'cuda' or 'cpu'